# Pandas Basics

In [43]:
# Pandas is a high-level Python library for data manipulation, analysis, and preprocessing.
# It provides two primary data structures:
# Series → 1D labeled array
# DataFrame → 2D labeled table (rows + columns)
# Internally Pandas is built on top of NumPy, so it leverages fast array computations but adds: labels (row/column names), heterogeneous data support, rich data operations



# Pandas is a Python library used for data manipulation and analysis. It provides labeled data structures like Series and DataFrame to handle structured data efficiently.
# NumPy, on the other hand,is used for numerical computations with homogeneous arrays. While NumPy is faster and suited for mathematical operations, Pandas is more user-friendly and suitable for handling real-world datasets

# Pandas Series

In [44]:
# Pandas Series = is like a column in a table , it is a 1D array holding data of any type

import pandas as pd
import numpy as np

# Creating pandas series from LISTS

#String:-

country = ['INDIA','USA', 'CHINA','RUSSIA']
pd.Series(country)            # if bydefault the dtype = object then we can say that it is string datatype

0     INDIA
1       USA
2     CHINA
3    RUSSIA
dtype: object

In [45]:
# From Integers:-
runs = [13,24,56,78,200]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    200
dtype: int64

In [46]:
# By Making them in (Custom Index):-
marks = [67,57,89,100]
subjects = ['EVS', 'DAA', 'DSA','DBMS']
pd.Series(marks, index = subjects, name = 'SEM2') # name is basically used to set name for an series

EVS      67
DAA      57
DSA      89
DBMS    100
Name: SEM2, dtype: int64

## Pandas Series from DICT

In [47]:
marks = {
    'EVS': 67,
    'DAA': 57,
    'DSA': 89,
    'DBMS': 100
}
marks_series = pd.Series(marks, name = 'NEW DICTIONARY')
marks_series

EVS      67
DAA      57
DSA      89
DBMS    100
Name: NEW DICTIONARY, dtype: int64

## Series Attributes:-

In [48]:
# Size:- gives number of elements in the series
marks_series.size

#dtype:- gives datatype
marks_series.dtype

# name:- returns the name specified for an series
marks_series.name

# index:- gives all index for the series
marks_series.index

# isunique:- gives true for all unique items in the series
marks_series.is_unique

# values:- returns the all values that are stored in the series
marks_series.values

array([ 67,  57,  89, 100])

## Series using read_csv

In [49]:
subs = pd.read_csv('/subs.csv').squeeze()
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [50]:
# with 2 columns:-
vk = pd.read_csv('/kohli_ipl.csv',index_col = 'match_no').squeeze()

In [51]:
# with 2 columns:- squeeze = “Remove extra dimensions if they are unnecessary” = converts -> single-column DataFrame -> Series
movies = pd.read_csv('/bollywood.csv',index_col = 'movie').squeeze()
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

## Series Methods:-

In [52]:
# head = by default it gives starting 5 data from datasets & canbe any number is specifed(UPTO),and tail() = gives last(bottom) 5 data from datasets
subs.head()
subs.tail(10)

355    149
356    156
357    177
358    210
359    209
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [53]:
# sample:- gives one row randomly -> used when the data is somewhat biased
movies.sample()

movie
Jab We Met    Shahid Kapoor
Name: lead, dtype: object

In [54]:
# value_counts ->data me each item ka frequency (returns)
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [55]:
#sort_values-> sort values in order(ascending or descending)
vk.sort_values()
vk.sort_values(ascending = False).head(1).values[0] # example of method chaining!!!!  O/P of another method is I/P of another method

# vk.sort_values(inplace=True) inplace gives us changes in the original dataset

np.int64(113)

In [56]:
# sort_index = used to sort index in alphabetical order
movies.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

# Series Maths Method

In [70]:
# count:- used to count total no. of items in series , it doesnt count missing values in the series, similar to size(series attributes)-> but it also counts number of missing values in the series
vk.count()

# sum & Product:-
subs.sum()
subs.prod()


# mean,median,mode,std,var
subs.mean()
subs.median()
subs.mode() # aparticular values the comes more in frequency
subs.std()
subs.var()


# min/max
subs.min()
subs.max()

# describe() gives everything at one place
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

# Series Indexing:-

In [71]:
# Integer indexing:-
x = pd.Series([12,13,14,15,16,17,18])
x[1]

np.int64(13)

In [75]:
# negative indexing wont work in panda's
# slicing:-
vk[5:12]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
12    38
Name: runs, dtype: int64