# Pandas Basics

In [2]:
# Pandas is a high-level Python library for data manipulation, analysis, and preprocessing.
# It provides two primary data structures:
# Series → 1D labeled array
# DataFrame → 2D labeled table (rows + columns)
# Internally Pandas is built on top of NumPy, so it leverages fast array computations but adds: labels (row/column names), heterogeneous data support, rich data operations



# Pandas is a Python library used for data manipulation and analysis. It provides labeled data structures like Series and DataFrame to handle structured data efficiently.
# NumPy, on the other hand,is used for numerical computations with homogeneous arrays. While NumPy is faster and suited for mathematical operations, Pandas is more user-friendly and suitable for handling real-world datasets

# Pandas Series

In [1]:
# Pandas Series = is like a column in a table , it is a 1D array holding data of any type

import pandas as pd
import numpy as np

# Creating pandas series from LISTS

#String:-

country = ['INDIA','USA', 'CHINA','RUSSIA']
pd.Series(country)            # if bydefault the dtype = object then we can say that it is string datatype

0     INDIA
1       USA
2     CHINA
3    RUSSIA
dtype: object

In [4]:
# From Integers:-
runs = [13,24,56,78,200]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    200
dtype: int64

In [7]:
# By Making them in (Custom Index):-
marks = [67,57,89,100]
subjects = ['EVS', 'DAA', 'DSA','DBMS']
pd.Series(marks, index = subjects, name = 'SEM2') # name is basically used to set name for an series

EVS      67
DAA      57
DSA      89
DBMS    100
Name: SEM2, dtype: int64

## Pandas Series from DICT

In [14]:
marks = {
    'EVS': 67,
    'DAA': 57,
    'DSA': 89,
    'DBMS': 100
}
marks_series = pd.Series(marks, name = 'NEW DICTIONARY')
marks_series

EVS      67
DAA      57
DSA      89
DBMS    100
Name: NEW DICTIONARY, dtype: int64

## Series Attributes:-

In [ ]:
# Size:- gives number of elements in the series
marks_series.size

#dtype:- gives datatype
marks_series.dtype

# name:- returns the name specified for an series
marks_series.name

# index:- gives all index for the series
marks_series.index

# isunique:- gives true for all unique items in the series
marks_series.is_unique

# values:- returns the all values that are stored in the series
marks_series.values

## Series using read_csv

In [35]:
subs = pd.read_csv('/content/subs.csv').squeeze()
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [49]:
# with 2 columns:-
vk = pd.read_csv('/content/kohli_ipl.csv',index_col = 'match_no').squeeze()

In [ ]:
# with 2 columns:- squeeze = “Remove extra dimensions if they are unnecessary” = converts -> single-column DataFrame -> Series
movies = pd.read_csv('/content/bollywood (1).csv',index_col = 'movie').squeeze()
movies

## Series Methods:-

In [ ]:
# head = by default it gives starting 5 data from datasets & canbe any number is specifed(UPTO),and tail() = gives last(bottom) 5 data from datasets
subs.head()
subs.tail(10)

In [ ]:
# sample:- gives one row randomly -> used when the data is somewhat biased
movies.sample()

In [ ]:
# value_counts ->data me each item ka frequency (returns)
movies.value_counts()

In [ ]:
#sort_values-> sort values in order(ascending or descending)
vk.sort_values()
vk.sort_values(ascending = False).head(1).values[0] # example of method chaining!!!!  O/P of another method is I/P of another method

# vk.sort_values(inplace=True) inplace gives us changes in the original dataset

In [56]:
# sort_index = used to sort index in alphabetical order
movies.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object